config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  #validates :name,presence: true , length: {maximum: 30}

  def self.ransackable_attributes(auth_object = nil)
    %w[name ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result(distinct: true)
    @task = Task.new
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_url
    else
      render "index"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    if task.update_attributes(task_params)
      redirect_to tasks_url
    else
      render "edit"
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url
  end

    private
      def task_params
        params.require(:task).permit(:name)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700&display=swap" rel="stylesheet">
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @task, local: true do |f| %>
  <div class="form-group">
      <%= f.label "To edit" %>
      <%= f.text_field :name, class: "form-control", id: "task_name" ,placeholder: "New task" %>
  </div>

  <%= f.submit "Edit", class: "btn btn-primary edit-button-edit" %>
<% end %>

<%= link_to "Back",tasks_url, class: "btn btn-info edit-button-back" %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row p-5">
    <div class="col-md-4 mb-auto">
      <div class="search-form">
        <%= search_form_for(@q, class:"mb-5") do |f| %>
          <div class="form-group">
            <%= f.label "Search", class:"search-label" %>
            <%= f.search_field :name_cont, class:"form-control border-bar" , placeholder: "..." %>
          <%= link_to type:"submit",class:"btn btn-floating" do %>
            <%= fa_icon "search lg", class:"icon-c"%>
          <% end %>
          </div>
        <% end %>
      </div>
      <div class="create-form">
        <%= form_with model: @task, url:"/tasks", local: true do |f| %>
          <div class="form-group">
              <%= f.text_field :name, class: "form-control border-bar", id: "task_name" ,placeholder: "New task ..." %>
          </div>
          <%= f.submit "Create", class: "create-button" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <table class="table table-hover">
        <thead class="thead">
          <tr>
            <th>Task list</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @tasks.each do |task| %>
          <tbody>
            <tr class="content">
              <td class="col-md-8"><%= task.name  %></td>
              <td class="col-md-2">
                  <%= link_to edit_task_path(task),class:"btn btn-floating" do %>
                    <%= fa_icon "edit lg", class:"icon-a" %>
                  <% end %>
               </td>
               <td class="col-md-2">
                  <%= link_to task_path(task), method: :delete, class:"btn btn-floating" ,data: { confirm: "Sure?"} do %>
                    <%= fa_icon "trash lg", class:"icon-b" %>
                  <% end %>
               </td>
            </tr>
          </tbody>
        <% end %>
      </table>

    </div>
  </div>
</div>